2022-09-09 09:23:09,020 INFO    StreamThr :57283 [internal.py:wandb_internal():90] W&B internal server running at pid: 57283, started at: 2022-09-09 09:23:09.020548
2022-09-09 09:23:09,022 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: status
2022-09-09 09:23:09,022 DEBUG   SenderThread:57283 [sender.py:send_request():316] send_request: status
2022-09-09 09:23:09,023 DEBUG   SenderThread:57283 [sender.py:send():302] send: header
2022-09-09 09:23:09,023 INFO    WriterThread:57283 [datastore.py:open_for_write():75] open: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/run-613vffhp.wandb
2022-09-09 09:23:09,024 DEBUG   SenderThread:57283 [sender.py:send():302] send: run
2022-09-09 09:23:10,244 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: check_version
2022-09-09 09:23:10,264 INFO    SenderThread:57283 [dir_watcher.py:__init__():216] watching files in: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files
2022-09-09 09:23:10,265 INFO    SenderThread:57283 [sender.py:_start_run_threads():913] run started: 613vffhp with start time 1662695589.017806
2022-09-09 09:23:10,265 DEBUG   SenderThread:57283 [sender.py:send():302] send: summary
2022-09-09 09:23:10,265 INFO    SenderThread:57283 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2022-09-09 09:23:10,265 DEBUG   SenderThread:57283 [sender.py:send_request():316] send_request: check_version
2022-09-09 09:23:10,783 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: run_start
2022-09-09 09:23:10,798 DEBUG   HandlerThread:57283 [meta.py:__init__():35] meta init
2022-09-09 09:23:10,798 DEBUG   HandlerThread:57283 [meta.py:__init__():50] meta init done
2022-09-09 09:23:10,798 DEBUG   HandlerThread:57283 [meta.py:probe():216] probe
2022-09-09 09:23:10,804 DEBUG   HandlerThread:57283 [meta.py:_setup_git():206] setup git
2022-09-09 09:23:10,809 DEBUG   HandlerThread:57283 [meta.py:_setup_git():213] setup git done
2022-09-09 09:23:10,809 DEBUG   HandlerThread:57283 [meta.py:_save_pip():54] save pip
2022-09-09 09:23:10,809 DEBUG   HandlerThread:57283 [meta.py:_save_pip():68] save pip done
2022-09-09 09:23:10,809 DEBUG   HandlerThread:57283 [meta.py:_save_conda():75] save conda
2022-09-09 09:23:11,266 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_created():275] file/dir created: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/wandb-summary.json
2022-09-09 09:23:11,266 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_created():275] file/dir created: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/requirements.txt
2022-09-09 09:23:11,266 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_created():275] file/dir created: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/conda-environment.yaml
2022-09-09 09:23:13,134 DEBUG   HandlerThread:57283 [meta.py:_save_conda():85] save conda done
2022-09-09 09:23:13,134 DEBUG   HandlerThread:57283 [meta.py:probe():254] probe done
2022-09-09 09:23:13,166 DEBUG   SenderThread:57283 [sender.py:send():302] send: files
2022-09-09 09:23:13,166 INFO    SenderThread:57283 [sender.py:_save_file():1156] saving file wandb-metadata.json with policy now
2022-09-09 09:23:13,169 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: stop_status
2022-09-09 09:23:13,169 DEBUG   SenderThread:57283 [sender.py:send_request():316] send_request: stop_status
2022-09-09 09:23:13,170 DEBUG   SenderThread:57283 [sender.py:send():302] send: telemetry
2022-09-09 09:23:13,265 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/conda-environment.yaml
2022-09-09 09:23:13,266 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_created():275] file/dir created: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/wandb-metadata.json
2022-09-09 09:23:19,267 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: partial_history
2022-09-09 09:23:19,268 DEBUG   SenderThread:57283 [sender.py:send():302] send: history
2022-09-09 09:23:19,269 DEBUG   SenderThread:57283 [sender.py:send():302] send: summary
2022-09-09 09:23:19,270 INFO    SenderThread:57283 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2022-09-09 09:23:20,268 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/wandb-summary.json
2022-09-09 09:23:20,268 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_created():275] file/dir created: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/output.log
2022-09-09 09:23:22,268 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/output.log
2022-09-09 09:23:25,013 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: partial_history
2022-09-09 09:23:25,013 DEBUG   SenderThread:57283 [sender.py:send():302] send: history
2022-09-09 09:23:25,013 DEBUG   SenderThread:57283 [sender.py:send():302] send: summary
2022-09-09 09:23:25,015 INFO    SenderThread:57283 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2022-09-09 09:23:25,269 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/wandb-summary.json
2022-09-09 09:23:28,172 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: stop_status
2022-09-09 09:23:28,172 DEBUG   SenderThread:57283 [sender.py:send_request():316] send_request: stop_status
2022-09-09 09:23:28,269 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/output.log
2022-09-09 09:23:30,734 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: partial_history
2022-09-09 09:23:30,735 DEBUG   SenderThread:57283 [sender.py:send():302] send: history
2022-09-09 09:23:30,735 DEBUG   SenderThread:57283 [sender.py:send():302] send: summary
2022-09-09 09:23:30,736 INFO    SenderThread:57283 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2022-09-09 09:23:31,270 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/wandb-summary.json
2022-09-09 09:23:32,270 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/output.log
2022-09-09 09:23:36,488 DEBUG   HandlerThread:57283 [handler.py:handle_request():141] handle_request: partial_history
2022-09-09 09:23:36,489 DEBUG   SenderThread:57283 [sender.py:send():302] send: history
2022-09-09 09:23:36,489 DEBUG   SenderThread:57283 [sender.py:send():302] send: summary
2022-09-09 09:23:36,490 INFO    SenderThread:57283 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2022-09-09 09:23:37,271 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/wandb-summary.json
2022-09-09 09:23:38,170 DEBUG   SenderThread:57283 [sender.py:send():302] send: stats
2022-09-09 09:23:38,271 INFO    Thread-12 :57283 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/files/output.log
2022-09-09 09:23:39,940 ERROR   SenderThread:57283 [internal_api.py:execute():207] 404 response executing GraphQL.
2022-09-09 09:23:39,941 ERROR   SenderThread:57283 [internal_api.py:execute():208] {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-09-09 09:23:40,172 INFO    WriterThread:57283 [datastore.py:close():279] close: /home/frozenwolf/Desktop/neurIPS/Hecker_rl/wandb/run-20220909_092309-613vffhp/run-613vffhp.wandb
2022-09-09 09:23:40,239 INFO    HandlerThread:57283 [handler.py:finish():810] shutting down handler
2022-09-09 09:23:40,255 ERROR   StreamThr :57283 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 204, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1465, in upsert_run
    response = self.gql(
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 129, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/util.py", line 942, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/util.py", line 889, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 95, in _run
    self._debounce()
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 316, in _debounce
    self._sm.debounce()
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 387, in debounce
    self._debounce_config()
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 393, in _debounce_config
    self._api.upsert_run(
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/apis/normalize.py", line 61, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1465, in upsert_run
    response = self.gql(
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 129, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/util.py", line 942, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/frozenwolf/miniconda3/envs/citylearn/lib/python3.10/site-packages/wandb/util.py", line 889, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
